version: '3.7'
services:
    front-proxy:
        image: 'nginx:latest'
        restart: always
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - 80

    auth-proxy:
        image: 'voucher/vouch-proxy:latest'
        restart: always
        environment:
            VOUCH_CONFIG: '/vouch.yaml'
        volumes:
            - './vouch.yaml:/vouch.yaml'
        expose:
            - 8080

    ide:
        build: .
        restart: always
        expose:
            - 8080
        volumes:
            - './config.yaml:/config.yaml'
            - './user-home:/user-home'
            - './user-data:/user-data'
            - './projects:/projects'

